#!/usr/bin/env ruby
# frozen_string_literal: true

require 'jackhammer'
require 'jackhammer/cli'

begin
  cli = Jackhammer::CLI.new
  cli.parse
  cli.run
rescue StandardError => e
  raise e if $DEBUG

  warn e.message
  warn e.backtrace.join("\n")
  exit 1
end
